server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #  application:
  #    name: userservice
  cloud:
    #    nacos:
    #      server-addr: localhost:8848 #nacos服务器的地址
    discovery:
      cluster-name: HZ # 说明服务器在杭州
mybatis:
  type-aliases-package: com.atguigu.user.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
logging:
  level:
    com.atguigu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
pattern:
  name: 本地环境local
#eureka:
#  client:
#    fetch-registry: true # 不需要从注册中心里面抓取数据
#    register-with-eureka: true # 不需要从注册中心注册
#    service-url:
#      defaultZone: http://127.0.0.1:12233/eureka